### ISSUE TITLE
[Windows] Scene does not work as expected

### ISSUE THREAD

**Issue by napsio** [pmqtt/IntelliType#2]
If I start IntelliType on Windows (e.g. PowerShell) with the scene:

```yaml
scene:
  program: notepad
  wait: 5s
  countdown: true
```

Notepad starts, but the countdown only starts when I close Notepad.
